<?php
$mokuailang = array(
	//设置
	'tuangou_setting_tips'=>'<li>模块基本设置，本系统可以使用其他团购系统和使用系统自带团购系统两种方式</li><li>对于对discuz模板或者插件开发比较熟悉的可以选择其他团购系统，因为需要设置嵌入点，或者与微信墙总站联系，进行有偿服务。</li>',
	'tuangou_setting'=>'模块设置',
	'mokuai_type'=>'模块类型',
	'mokuai_system'=>'系统自带',
	'mokuai_zidingyi'=>'其他自定义',
	'mokuaitype_comment'=>'选择使用什么类型的微团购模块，建议使用系统自带的类型',
	'tuangoucat'=>'团购分类',
	'system_tuangoucat_comment'=>'团购分类，格式为<br />1=大类1<br />1.1=大类1的小类1<br />1.2=大类1的小类2<br />2=大类2<br />2.1=大类2的小类1<br />2.1.1=大类2的小类1的小类1<br />......<br />',
	'tuangoulink'=>'团购首页对应的链接',
	'tuangoulink_setting_comment'=>'您所使用的团购系统的首页面的链接地址',
	'tuangoucatlink'=>'团购分类页面对应的链接',
	'tuangoucatlink_setting_comment'=>'关键字采用{}括上，<br />比如分类链接地址为：http://www.wxq123.com/tuangou/cat.php?catid=3，<br />则填写http://www.wxq123.com/tuangou/cat.php?catid={catkey}',
	'zidingyi_tuangoucat_comment'=>'团购分类，格式为<br />catkey=大类1<br />catkey.catkey=大类1的小类1<br />catkey.catkey=大类1的小类2<br />catkey=大类2<br />catkey.catkey=大类2的小类1<br />catkey.catkey.catkey=大类2的小类1的小类1<br />......<br />',
	'shoplist'=>'商家列表页对应的页面链接',
	'zidingyi_shoplist_comment'=>'在商家列表页中，对应的商家的链接地址，关键字用{}括上<br />比如分类链接地址为：http://www.wxq123.com/tuangou/shoplist.php?shopid=213，<br />则填写http://www.wxq123.com/tuangou/shoplist.php?shopid={catkey}',
	'shopshow'=>'商家显示页对应的页面链接',
	'goodslist'=>'产品列表页的页面链接',
	'zidingyi_goodslist_comment'=>'在产品列表页中，对应的商家的链接地址，关键字用{}括上<br />比如分类链接地址为：http://www.wxq123.com/tuangou/goodslist.php?goodsid=213，<br />则填写http://www.wxq123.com/tuangou/goodslist.php?goodsid={catkey}',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	//商家
	'shop_list_tips'=>'商家列表',
	'shop_list'=>'商家列表',
	'displayorder'=>'排序',
	'shopname'=>'商家名称',
	'shoptype'=>'种类',
	'shopcat'=>'所属分类',
	'shopsbm'=>'商家识别码',
	'add_shop'=>'增加新的商家',
	'shop_edit'=>'编辑商家',
	'shop_edit_tips'=>'编辑商家注释',
	'shopname_comment'=>'商家名称',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	//产品
	''=>'',
	''=>'',
	''=>'',
	''=>'',
	''=>'',
);
?>